[package]
name = "obs-focus-window"
version = "0.1.0"
authors = ["Bennett Hardwick <me@bennetthardwick.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

members = [
  "obs-rs",
  "obs-sys",
  "motion-effects",
  "scroll-focus-filter"
]
