[package]
name = "obs-wrapper"
version = "0.1.1"
authors = ["Bennett Hardwick <me@bennetthardwick.com>"]
edition = "2018"
license = "GPL-2.0"
description = "Safe wrapper of obs-sys"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

members = [
  "obs-sys",
  "plugins/scroll-focus-filter"
]

[dependencies]
obs-sys = { path = "./obs-sys", version = "0.1.0" }
serde_json = "1.0.48"
